/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import persistencia.Vehicular;

/**
 *
 * @author cvelez
 */
public class VistaSimulacion extends javax.swing.JDialog {

    private final Modelo modelo;
    private Controlador controller;
    /**
     * Creates new form VistaSimulacion
     */
    public VistaSimulacion(Modelo thisModelo) {
        modelo = thisModelo;
        initComponents();
        asignarListener();
 
    }
    
    public Controlador getControlador() {
        if(controller == null){
            controller = new Controlador(this);
        }
        return controller;
    }

//    public Graphics pintarSemaforo() {
//    
//    }
//    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        //Semaforo vechicular
        g.setColor(Color.BLACK);
        g.drawRect(150, 70, 50, 70);
        
        g.setColor(Color.red);
        g.fillOval(155, 72, 20, 20);
        g.setColor(Color.black);
        g.drawOval(155, 72, 20, 20);
        
        g.setColor(Color.yellow);
        g.fillOval(155, 93, 20, 20);
        
        g.setColor(Color.green);
        g.fillOval(155, 114, 20, 20);
        
        
        //Semaforo peatonal
        g.setColor(Color.BLACK);
        g.drawRect(200, 70, 50, 60);
        
        g.setColor(Color.red);
        g.fillOval(205, 72, 20, 20);
        g.setColor(Color.black);
        g.drawOval(205, 72, 20, 20);
        
        g.setColor(Color.green);
        g.fillOval(205, 93, 20, 20);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        btnGroupVehicular = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_numConjunto = new javax.swing.JLabel();
        btnRojo = new javax.swing.JRadioButton();
        btnAmarillo = new javax.swing.JRadioButton();
        btnVerde = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Simulacion sistema semafórico");

        lbl_numConjunto.setText("Conjunto 1");

        btnGroupVehicular.add(btnRojo);
        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnGroupVehicular.add(btnAmarillo);
        btnAmarillo.setText("Amarillo");

        btnGroupVehicular.add(btnVerde);
        btnVerde.setText("Verde");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_numConjunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRojo)
                    .addComponent(btnVerde)
                    .addComponent(btnAmarillo))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numConjunto)
                    .addComponent(btnRojo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnAmarillo)
                .addGap(39, 39, 39)
                .addComponent(btnVerde))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        
    }//GEN-LAST:event_btnRojoActionPerformed

    
    private void asignarListener() {
        btnRojo.addActionListener(getControlador());
        btnAmarillo.addActionListener(getControlador());
        btnVerde.addActionListener(getControlador());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAmarillo;
    private javax.swing.ButtonGroup btnGroupVehicular;
    private javax.swing.JRadioButton btnRojo;
    private javax.swing.JRadioButton btnVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_numConjunto;
    // End of variables declaration//GEN-END:variables
    
    
    public ButtonGroup getBtnGroupVehicular() {
        return btnGroupVehicular;
    }
    
    public JRadioButton getBtnRojo() {
        return btnRojo;
    }

    public JRadioButton getBtnAmarillo() {
        return btnAmarillo;
    }

    public JRadioButton getBtnVerde() {
        return btnVerde;
    }
    
    public Modelo getModelo() {
        return modelo;
    }

}
